spring.application.name=security

app.jwt.secret=${}
app.jwt.access-expiration-ms=900000      
app.jwt.refresh-expiration-ms=1209600000 
#Username & password m\u1EB7c \u0111\u1ECBnh
app.admin.master-key=${ADMIN_MASTER_KEY}
app.admin.username=${ADMIN_USERNAME}
app.admin.password=${ADMIN_PASSWORD}
